feat: add check_release_version script, make it reusable Add check that validates before committing to branch if branch name release/X.Y.Z is correctly set in VERSION file (used by other automation) Make this reusable elsewhere

diff --git a/scripts/git-hooks/pre-commit b/scripts/git-hooks/pre-commit
--- a/scripts/git-hooks/pre-commit
+++ b/scripts/git-hooks/pre-commit
@@ -13,3 +13,7 @@ else
   exit 1
 fi
 
+if ! bash scripts/check_release_version.sh --version-file VERSION; then
+  echo "[pre-commit] Release branch VERSION check failed." >&2
+  exit 1
+fi
